---
# Ethereum Execution Layer Clients

- name: Configure execution layer instance(s)
  hosts: localhost
  roles:
  - role: ../roles/cloud-node
    vars:
      cloud_provider: aws
      instance_name: eth-execution
      instance_tag: geth
      security_group_name: geth-sg
      ssh_public_key: dev
      ssh_private_key_path: ~/.ssh/dev.pem
      ingress_ports:
      - proto: tcp
        ports:
        - 22
        - 8545
        - 6060
        - 4000
        cidr_ip: 0.0.0.0/0

- name: Configure Ethereum execution layer clients
  hosts: geth
  remote_user: ubuntu
  become: true
  roles:
  - role: ../roles/basic-service
    vars:
      setup_mode: systemd
      name: geth
      binary_url: https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.14.5-0dd173a7.tar.gz
      command: >
        /usr/local/bin/geth-linux-amd64-1.14.5-0dd173a7/geth --config /config/geth.toml --sepolia --http --metrics
      cpus: 100%
      memory: 2G
      config:
        geth.toml:
          destinationPath: /config/geth.toml
          data: |
            [Eth]
            NetworkId = 11155111  # Sepolia network ID
            SyncMode = "snap"

            [Node]
            DataDir = "/home/ubuntu/.ethereum/sepolia"
            HTTPHost = "0.0.0.0"
            HTTPPort = 8545
            HTTPModules = ["net", "web3", "eth"]
            WSHost = "0.0.0.0"
            WSPort = 8546
            WSModules = ["net", "web3", "eth"]

            [Metrics]
            HTTP = "0.0.0.0"
            Port = 6060

  - role: ../roles/basic-service
    vars:
      setup_mode: systemd
      name: prysm-beacon
      binary_url: https://github.com/prysmaticlabs/prysm/releases/download/v5.0.4/beacon-chain-v5.0.4-linux-amd64
      command: >
        beacon-chain-v5.0.4-linux-amd64 --accept-terms-of-use --sepolia --jwt-secret=/home/ubuntu/.ethereum/sepolia/geth/jwtsecret --datadir=/home/ubuntu --execution-endpoint=http://127.0.0.1:8551
        --checkpoint-sync-url=https://sepolia.beaconstate.info --genesis-beacon-api-url=https://sepolia.beaconstate.info --rpc-host 0.0.0.0
      cpus: 100%
      memory: 2G

# Ethereum Consensus Layer Clients

- name: Show inventory details
  hosts: localhost
  tasks:
  - name: Get the public IP of the first host in the "geth" group
    set_fact:
      first_geth_host_ip: "{{ hostvars[groups['geth'][0]].ansible_host }}"
  
  - name: Debug print the public IP
    debug:
      msg: "The public IP of the first host in the 'geth' group is {{ first_geth_host_ip }}"

- name: Configure consensus layer instance(s)
  hosts: localhost
  roles:
  - role: ../roles/cloud-node
    vars:
      cloud_provider: aws
      instance_name: eth-consensus
      instance_tag: prysm-validator
      security_group_name: validator-sg
      ssh_public_key: dev
      ssh_private_key_path: ~/.ssh/dev.pem
      ingress_ports:
      - proto: tcp
        ports:
        - 22
        cidr_ip: 0.0.0.0/0

- name: Configure Ethereum consensus layer clients
  hosts: prysm-validator
  remote_user: ubuntu
  become: true
  roles:
  - role: ../roles/basic-service
    vars:
      setup_mode: systemd
      name: prysm-validator
      binary_url: https://github.com/prysmaticlabs/prysm/releases/download/v5.0.4/validator-v5.0.4-linux-amd64
      command: >
        /usr/local/bin/validator-v5.0.4-linux-amd64 --accept-terms-of-use
        --beacon-rpc-provider {{ hostvars[groups['geth'][0]].ansible_host }}:4000 --sepolia
        --wallet-dir /home/ubuntu/.eth2validators/prysm-wallet-v2 --wallet-password-file /home/ubuntu/password
        --beacon-rest-api-provider http://{{ hostvars[groups['geth'][0]].ansible_host }}:3500
      cpus: 100%
      memory: 2G