---
- name: Manage storage/data setup
  ansible.builtin.include_tasks: common/storage-setup.yml

- name: Setup service infrastructure topology
  ansible.builtin.include_tasks: "{{ setup_mode }}/setup.yml"

- name: Manage networking and IP tables setup
  when: setup_iptables|bool
  ansible.builtin.include_tasks: common/network-setup.yml
