---
- name: Uninstall service container
  community.docker.docker_container:
    name: "{{ name }}"
    state: absent
    purge_networks: true
  listen: Container uninstall

- name: Remove generated service config files
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ item.value.destinationPath }}"
    state: absent
  with_dict: "{{ config }}"
  listen: Container uninstall

- name: Remove service data directory
  become: true
  ansible.builtin.file:
    path: "{{ hostDataDir }}"
    state: absent
  listen: Container uninstall
