---
- name: Determine service ingress port list for iptables config
  ansible.builtin.set_fact:
    ingress_list: "{{ ingress_list + [item.value.ingressPort | string] }}"
  with_dict: "{{ ports }}"

- name: Allow service ingress ports in iptables setup
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: "{{ ingress_list }}"
    jump: ACCEPT
