{{ range $key, $value := $.Values.clusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{template "basic-service.name" $}}-{{$key}}-clusterrole-binding
  labels:
    {{- include "basic-service.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{template "basic-service.name" $}}-{{$key}}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{template "basic-service.name" $}}-{{$key}}-clusterrole-binding
    namespace: {{ $value.serviceAccountName | default .Release.Namespace }}
{{- end }}
