{{ range $key, $value := $.Values.clusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{template "basic-service.name" $}}-{{$key}}-clusterrole
  labels:
    {{- include "basic-service.labels" . | nindent 4 }}
rules:
{{- toYaml $value.rules | nindent 0 }}
{{- end }}
