apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{template "basic-service.name" .}}-hpa
  namespace: {{.Values.namespace}}
  labels:
    app: {{template "basic-service.name" .}}
    {{- if .Values.labels }}
    {{- include "basic-service.labels" $ | indent 4}}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{template "basic-service.name" .}}-deployment
  minReplicas: {{.Values.minReplicas | default "1"}}
  maxReplicas: {{.Values.maxReplicas | default "3"}}
  targetCPUUtilizationPercentage: {{.Values.targetCPUUtilizationPercentage | default "50"}}
