{{ range $key, $value := $.Values.serviceRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{template "basic-service.name" $}}-{{$key}}-role-binding
  namespace: {{ $value.namespace | default $.Values.namespace }}
  labels:
    app: {{template "basic-service.name" $}}
    {{- if $.Values.labels }}
    {{- include "basic-service.labels" $ | indent 4}}
    {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ $value.serviceAccount | default $.Values.serviceAccountName }}
    namespace: {{$.Values.namespace}}
roleRef:
  kind: Role
  name: {{template "basic-service.name" $}}-{{$key}}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
