---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic-service.name" . }}-env
  labels:
    {{- include "basic-service.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
