---
### Common ###
# name:
destination_directory: /usr/local/bin
setup_mode: container
work_dir: /var/tmp

command:

ports: {}
# example-port1:
#   ingressPort: 80
#   servicePort: 2411
# example-port2:
#   ingressPort: 443
#   servicePort: 2412

config: {}
# example-config1:
#   destinationPath: /config/example-1.yaml
#   data: |
#     a: 1
#     b: 2
#     c:
#       d: 3
# example-config2:
#   destinationPath: /config/example-2.toml
#   data: |
#     [a]
#     b=1
#     [c]
#     d=2
# example-entrypoint:
#   destinationPath: /docker-entrypoint.d/example-entrypoint.sh
#   mode: 0755
#   data: |
#     !/bin/bash
#
#     echo "Hello World!"

config_env: {}
# RUN_ARGS: --help

data_dirs: {}
# chain-data:
#   hostPath: /mnt/data
#   appPath: /app/data

restart_policy: unless-stopped
uninstall: false
volume_list: []
port_list: []

### Container ###
image:
resources:
  cpuLimit: 1
  memRequest: 1G
  memLimit: 1G

### Systemd ###
binary_url:
# (Optional) Override the binary file name after moving it to the destination directory
binary_file_name_override:

cpus: 100%
memory: 1G

systemd: {}
# unit_properties: {}
# service_properties: {}
# install_properties: {}

systemd_environment_directive: ""

setup_iptables: false
